export const DiagnosticCodes = {
  PARSE_ERROR: 'ASPEC_PARSE_001',
  SCHEMA_ERROR: 'ASPEC_SCHEMA_001',
  STYLE_NO_PURPOSE: 'ASPEC_STYLE_001',
  STYLE_NO_MODULE_DESC: 'ASPEC_STYLE_002',
  STYLE_NO_PROCESS_DESC: 'ASPEC_STYLE_003',
  STYLE_NO_DECOMP: 'ASPEC_STYLE_004',
  STYLE_NO_OTHERS: 'ASPEC_STYLE_005',
  STYLE_DUPLICATE_ID: 'ASPEC_STYLE_006',
  REFINE_TYPE_FALLBACK: 'ASPEC_REFINE_001',
  BOOK_ALIGN_NO_FUNCTIONS: 'BOOK_ALIGN_001',
  BOOK_ALIGN_DATA_REFS: 'BOOK_ALIGN_002',
  BOOK_ALIGN_CONSTRAINT_REFS: 'BOOK_ALIGN_003',
  BOOK_ALIGN_NO_CONSTRAINTS: 'BOOK_ALIGN_004',
  BOOK_ALIGN_SYMMETRIC: 'BOOK_ALIGN_005',
  BOOK_ALIGN_SHARED_DATA: 'BOOK_ALIGN_006',
  BOOK_ALIGN_FUNCTION_FORMAT: 'BOOK_ALIGN_007',
  BOOK_ALIGN_DATA_FORMAT: 'BOOK_ALIGN_008',
  BOOK_ALIGN_CONSTRAINT_FORMAT: 'BOOK_ALIGN_009'
} as const

export function createDiagnostic(
  code: string,
  message: string,
  severity: 'error' | 'warning' | 'info',
  path?: string
) {
  return { code, message, severity, path }
}
